"use client";

import "./globals.css";
import "./dynamic_bg.css";
import { Work_Sans, PT_Sans } from "next/font/google";
import { useEffect, useState } from "react";
import { SocialIcon } from "react-social-icons";

const mainFont = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const splashFont = Work_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "MIRIMOMEKIKU",
  description: "Generated by create next app",
};

const LeftLayout = (props) => {
  return (
    <>
      <div className="flex-row 2xl:fixed absolute xl:top-16 xl:left-8 hidden xl:flex duration-500 delay-0 transition-all hover:scale-125">
        <SocialIcon
          url="https://facebook.com/mirimomekiku"
          fgColor="black"
          bgColor="white"
        ></SocialIcon>
      </div>
      <div className="flex-row 2xl:fixed absolute xl:top-32 xl:left-8 hidden xl:flex duration-500 delay-0 transition-all hover:scale-125">
        <SocialIcon
          url="https://github.com/dlord213"
          fgColor="black"
          bgColor="white"
        ></SocialIcon>
      </div>
    </>
  );
};

const FirstDynamicBG = () => {
  return (
    <>
      <div
        id="dynamic-bg-wrap"
        className="circles opacity-0 transition-all duration-[1s] delay-0 md:block hidden"
      >
        <svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid slice">
          <defs>
            <radialGradient
              id="Gradient1"
              cx="50%"
              cy="50%"
              fx="0.441602%"
              fy="50%"
              r=".5"
            >
              <animate
                attributeName="fx"
                dur="34s"
                values="0%;3%;0%"
                repeatCount="indefinite"
              ></animate>
              <stop offset="0%" stopColor="rgba(255, 0, 255, 1)"></stop>
              <stop offset="100%" stopColor="rgba(255, 0, 255, 0)"></stop>
            </radialGradient>
            <radialGradient
              id="Gradient2"
              cx="50%"
              cy="50%"
              fx="2.68147%"
              fy="50%"
              r=".5"
            >
              <animate
                attributeName="fx"
                dur="23.5s"
                values="0%;3%;0%"
                repeatCount="indefinite"
              ></animate>
              <stop offset="0%" stopColor="rgba(255, 255, 0, 1)"></stop>
              <stop offset="100%" stopColor="rgba(255, 255, 0, 0)"></stop>
            </radialGradient>
            <radialGradient
              id="Gradient3"
              cx="50%"
              cy="50%"
              fx="0.836536%"
              fy="50%"
              r=".5"
            >
              <animate
                attributeName="fx"
                dur="21.5s"
                values="0%;3%;0%"
                repeatCount="indefinite"
              ></animate>
              <stop offset="0%" stopColor="rgba(0, 255, 255, 1)"></stop>
              <stop offset="100%" stopColor="rgba(0, 255, 255, 0)"></stop>
            </radialGradient>
            <radialGradient
              id="Gradient4"
              cx="50%"
              cy="50%"
              fx="4.56417%"
              fy="50%"
              r=".5"
            >
              <animate
                attributeName="fx"
                dur="23s"
                values="0%;5%;0%"
                repeatCount="indefinite"
              ></animate>
              <stop offset="0%" stopColor="rgba(0, 255, 0, 1)"></stop>
              <stop offset="100%" stopColor="rgba(0, 255, 0, 0)"></stop>
            </radialGradient>
            <radialGradient
              id="Gradient5"
              cx="50%"
              cy="50%"
              fx="2.65405%"
              fy="50%"
              r=".5"
            >
              <animate
                attributeName="fx"
                dur="24.5s"
                values="0%;5%;0%"
                repeatCount="indefinite"
              ></animate>
              <stop offset="0%" stopColor="rgba(0,0,255, 1)"></stop>
              <stop offset="100%" stopColor="rgba(0,0,255, 0)"></stop>
            </radialGradient>
            <radialGradient
              id="Gradient6"
              cx="50%"
              cy="50%"
              fx="0.981338%"
              fy="50%"
              r=".5"
            >
              <animate
                attributeName="fx"
                dur="25.5s"
                values="0%;5%;0%"
                repeatCount="indefinite"
              ></animate>
              <stop offset="0%" stopColor="rgba(255,0,0, 1)"></stop>
              <stop offset="100%" stopColor="rgba(255,0,0, 0)"></stop>
            </radialGradient>
          </defs>
          <rect x="0" y="0" width="100%" height="100%" fill="url(#Gradient4)">
            <animate
              attributeName="x"
              dur="20s"
              values="25%;0%;25%"
              repeatCount="indefinite"
            />
            <animate
              attributeName="y"
              dur="21s"
              values="0%;25%;0%"
              repeatCount="indefinite"
            />
            <animateTransform
              attributeName="transform"
              type="rotate"
              from="0 50 50"
              to="360 50 50"
              dur="17s"
              repeatCount="indefinite"
            />
          </rect>
          <rect x="0" y="0" width="100%" height="100%" fill="url(#Gradient5)">
            <animate
              attributeName="x"
              dur="23s"
              values="0%;-25%;0%"
              repeatCount="indefinite"
            />
            <animate
              attributeName="y"
              dur="24s"
              values="25%;-25%;25%"
              repeatCount="indefinite"
            />
            <animateTransform
              attributeName="transform"
              type="rotate"
              from="0 50 50"
              to="360 50 50"
              dur="18s"
              repeatCount="indefinite"
            />
          </rect>
          <rect x="0" y="0" width="100%" height="100%" fill="url(#Gradient6)">
            <animate
              attributeName="x"
              dur="25s"
              values="-25%;0%;-25%"
              repeatCount="indefinite"
            />
            <animate
              attributeName="y"
              dur="26s"
              values="0%;-25%;0%"
              repeatCount="indefinite"
            />
            <animateTransform
              attributeName="transform"
              type="rotate"
              from="360 50 50"
              to="0 50 50"
              dur="19s"
              repeatCount="indefinite"
            />
          </rect>
          <rect
            x="13.744%"
            y="1.18473%"
            width="100%"
            height="100%"
            fill="url(#Gradient1)"
            transform="rotate(334.41 50 50)"
          >
            <animate
              attributeName="x"
              dur="20s"
              values="25%;0%;25%"
              repeatCount="indefinite"
            ></animate>
            <animate
              attributeName="y"
              dur="21s"
              values="0%;25%;0%"
              repeatCount="indefinite"
            ></animate>
            <animateTransform
              attributeName="transform"
              type="rotate"
              from="0 50 50"
              to="360 50 50"
              dur="7s"
              repeatCount="indefinite"
            ></animateTransform>
          </rect>
          <rect
            x="-2.17916%"
            y="35.4267%"
            width="100%"
            height="100%"
            fill="url(#Gradient2)"
            transform="rotate(255.072 50 50)"
          >
            <animate
              attributeName="x"
              dur="23s"
              values="-25%;0%;-25%"
              repeatCount="indefinite"
            ></animate>
            <animate
              attributeName="y"
              dur="24s"
              values="0%;50%;0%"
              repeatCount="indefinite"
            ></animate>
            <animateTransform
              attributeName="transform"
              type="rotate"
              from="0 50 50"
              to="360 50 50"
              dur="12s"
              repeatCount="indefinite"
            ></animateTransform>
          </rect>
          <rect
            x="9.00483%"
            y="14.5733%"
            width="100%"
            height="100%"
            fill="url(#Gradient3)"
            transform="rotate(139.903 50 50)"
          >
            <animate
              attributeName="x"
              dur="25s"
              values="0%;25%;0%"
              repeatCount="indefinite"
            ></animate>
            <animate
              attributeName="y"
              dur="12s"
              values="0%;25%;0%"
              repeatCount="indefinite"
            ></animate>
            <animateTransform
              attributeName="transform"
              type="rotate"
              from="360 50 50"
              to="0 50 50"
              dur="9s"
              repeatCount="indefinite"
            ></animateTransform>
          </rect>
        </svg>
      </div>
    </>
  );
};

const SplashPage = () => {
  const [textAnimation, setTextAnimation] = useState("opacity-0");
  const [text, setText] = useState("");
  const [splashBodyStyle, setSplashBodyStyle] = useState(
    " bg-slate-900 text-white"
  );

  useEffect(() => {
    setTimeout(() => {
      setTextAnimation("opacity-100");
    }, 500);

    setTimeout(() => {
      setText("m");
    }, 600);
    setTimeout(() => {
      setText("mi");
    }, 900);
    setTimeout(() => {
      setText("miri");
    }, 1100);
    setTimeout(() => {
      setText("mirim");
    }, 1200);
    setTimeout(() => {
      setText("mirimo");
    }, 1400);
    setTimeout(() => {
      setText("mirimome");
    }, 1500);
    setTimeout(() => {
      setText("mirimomek");
    }, 1600);
    setTimeout(() => {
      setText("mirimomeki");
    }, 1800);
    setTimeout(() => {
      setText("mirimomekik");
    }, 1900);
    setTimeout(() => {
      setText("mirimomekiku");
    }, 2000);
    setTimeout(() => {
      setTextAnimation("opacity-0");
    }, 2500);
    setTimeout(() => {
      setTextAnimation("opacity-100");
    }, 3000);
    setTimeout(() => {
      setSplashBodyStyle(" bg-white text-black");
    }, 3500);
    setTimeout(() => {
      setTextAnimation("opacity-100");
    }, 3700);
    setTimeout(() => {
      setTextAnimation("opacity-0");
    }, 5000);
  }, []);

  return (
    <html lang="en">
      <body
        className={
          splashFont.className +
          " select-none transition-all duration-[1s] delay-0 " +
          splashBodyStyle
        }
      >
        <div className="items-center justify-center flex h-screen w-full">
          <h1
            className={
              "font-bold lg:text-8xl text-4xl transition-all delay-0 duration-500 " +
              textAnimation
            }
          >
            {text}
          </h1>
        </div>
      </body>
    </html>
  );
};

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState(" bg-white text-black accent-sky-600");
  const [buttonTheme, setBtnTheme] = useState(
    "text-black lg:border-b-2 border-black hover:bg-black hover:text-white"
  );

  const [themeState, setThemeState] = useState(0); // 0 = light | 1 = dark

  const [pageState, setPageState] = useState(0);

  useEffect(() => {

    const windowWidth = window.innerWidth

    setTimeout(() => {
      setPageState(1);
    }, 5500);

    setTimeout(() => {
      if (windowWidth > 1024) {
        document.getElementById("dynamic-bg-wrap").classList.remove("opacity-0");
        document.getElementById("dynamic-bg-wrap").classList.add("opacity-20");
      }
    }, 7000);
  }, [pageState]);

  if (pageState == 0) {
    return <SplashPage />;
  } else {
    return (
      <html lang="en">
        <body className={splashFont.className + theme + " select-none scroll-smooth"}>
          <FirstDynamicBG />
          {children}

          <LeftLayout theme={buttonTheme} />

          <button
            className={
              "fixed bottom-[5rem] left-[0rem] hidden min-[1440px]:block transition-all ease-in-out delay-0 duration-500 p-2 -rotate-90 " +
              buttonTheme
            }
            type="toggle"
            onClick={() => {
              if (themeState == 1) {
                setThemeState(0);
                setTheme(" bg-white text-black");
                setBtnTheme(
                  " text-black border-b-2 border-black p-4 hover:bg-black hover:text-white"
                );
                document
                  .getElementById("dynamic-bg-wrap")
                  .classList.remove("opacity-10");
                document
                  .getElementById("dynamic-bg-wrap")
                  .classList.add("opacity-20");
              }
              if (themeState == 0) {
                setThemeState(1);
                setTheme(" bg-slate-950 text-white");
                setBtnTheme(
                  " text-white border-b-2 border-white p-4 hover:bg-white hover:text-black"
                );
                document
                  .getElementById("dynamic-bg-wrap")
                  .classList.remove("opacity-20");
                document
                  .getElementById("dynamic-bg-wrap")
                  .classList.add("opacity-10");
              }
            }}
          >
            switch theme
          </button>
        </body>
      </html>
    );
  }
}
