export const hiphopImgs = [
  { src: "/assets/images/albums/hip-hop/1.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/2.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/2.png", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/3 (2).jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/3.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/4.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/5.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/6.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/6.png", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/7 (2).jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/7.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/8.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/9.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/10.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/11.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/12.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/13.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/14.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/15.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/16.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/17.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/21.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/26.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/27.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/31.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/hip-hop/33.jpg", width: 320, height: 320 },
];

export const indieImgs = [
  { src: "/assets/images/albums/indie/1.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/2.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/3 (2).jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/3.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/4.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/5.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/6.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/7.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/8.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/9.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/10.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/11.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/12.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/13.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/13.webp", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/14.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/28.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie/32.jpg", width: 320, height: 320 },
];

export const indieRockImgs = [
  { src: "/assets/images/albums/indie-rock/1.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/2.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/3.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/4.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/5.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/6.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/7.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/8.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/11.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/18.png", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/20.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/22.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/23.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/24.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/indie-rock/25.jpg", width: 320, height: 320 },
];

export const jpKrImgs = [
  {
    src: "/assets/images/albums/japanese-korean/1.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/2.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/3.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/4.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/5.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/6.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/7.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/8.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/9.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/10.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/11.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/12.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/13.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/14.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/15.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/16.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/17.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/18.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/19.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/20.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/21.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/22.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/23.webp",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/24.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/25.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/26.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/27.jpg",
    width: 320,
    height: 320,
  },
  {
    src: "/assets/images/albums/japanese-korean/for lovers.jpg",
    width: 320,
    height: 320,
  },
];

export const popImgs = [
  { src: "/assets/images/albums/pop/1.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/2.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/3.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/4.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/5.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/6.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/7.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/8.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/9.png", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/10.png", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/12.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/13.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/15.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/pop/19.jpg", width: 320, height: 320 },
];

export const rnbSoulImgs = [
  { src: "/assets/images/albums/rnb-soul/1.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/2.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/3.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/4.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/5.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/6.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/7.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/8.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/9.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/10.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/10.png", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/11.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/12.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/13.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/14.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/15.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/16.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/17.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/17.png", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/18.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/19.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/20.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/21.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/22.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/23.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/24.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/25.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/26.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/27.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/29.jpg", width: 320, height: 320 },
  { src: "/assets/images/albums/rnb-soul/30.jpg", width: 320, height: 320 },
];
